version: '3.7'

services:
  
  jenkins:
    image: jenkins/jenkins
    deploy:
      placement:
        constraints:
          - node.labels.jenkins == jenkins
      replicas: 1 
      labels:
        - traefik.port=8080
        - traefik.frontend.rule=Host:jenkins.horsesizedduck.site   
    volumes:
      - proxy_jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock     
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  proxy_jenkins_data:
